### ISSUE TITLE
Confirm `table_entry_size`

### ISSUE THREAD

**Issue by fw-brice** [riscv/v8#376]
[This FIXME](https://github.com/v8-riscv/v8/blob/fc127d87bc4aa87e9729442d5ead953d01eb9112/src/deoptimizer/riscv64/deoptimizer-riscv64.cc#L16) needs to be confirmed.

```cpp
// Maximum size of a table entry generated below.
// FIXME(RISCV): Is this value correct?
const int Deoptimizer::table_entry_size_ = 2 * kInstrSize;
```

**Comment by luyahan** [comment]
The const number const int Deoptimizer::table_entry_size_ is deleted from  deoptimizer-riscv64.cc
