### ISSUE TITLE
[upstream main] wasm-spec-tests/conversions

### ISSUE THREAD

**Issue by ZhengLiu2825** [riscv/v8#504]
**Describe the bug**

wasm-spec-tests/conversions fails randomly.

**To Reproduce**

Fetch the latest main branch (commit id: 8bc7f45337c453482b552b7dd872bc62af6ff34a).

Let `FLAG_riscv_c_extension` be `true.`

Execute `tools/dev/gm.py riscv64.release.checkall` multiple times. 

(I executed it 11 times. This failure appeared 2 times.)

**Expected behavior**

> === wasm-spec-tests/conversions ===
wasm-function[6]:0xfd: RuntimeError: unreachable
RuntimeError: unreachable
    at wasm://wasm/9ca05c5a:wasm-function[6]:0xfd
    at call (/path/v8/test/wasm-spec-tests/tests/conversions.js:77:32)
    at /path/v8cur/v8/test/wasm-spec-tests/tests/conversions.js:921:11
    at run (/path/v8cur/v8/test/wasm-spec-tests/tests/conversions.js:90:3)
    at /path/v8cur/v8/test/wasm-spec-tests/tests/conversions.js:921:1
Command: out/riscv64.release/d8 --test test/wasm-spec-tests/tests/conversions.js --random-seed=-1328885165 --nohard-abort --testing-d8-test-runner --experimental-wasm-reftypes
--- FAILED ---

**Comment by qjivy** [comment]
According to https://ci.rvperf.org/job/v8-upstream-master/486/console， this bug would also happen w/o the c_ext be true. 
And it's a randomly crash.

**Comment by qjivy** [comment]
fix by https://chromium-review.googlesource.com/c/v8/v8/+/3114159
