### ISSUE TITLE
error: narrowing conversion

### ISSUE THREAD

**Issue by andreas-schwab** [riscv/v8#505]
https://build.opensuse.org/package/live_build_log/home:Andreas_Schwab:Factory/nodejs16/r/riscv64

../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc: In member function 'void v8::internal::Decoder::DecodeRAType(v8::internal::Instruction*)':
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:897:10: error: narrowing conversion of 'v8::internal::RO_AMOMIN_W' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
  897 |     case RO_AMOMIN_W:
      |          ^~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:900:10: error: narrowing conversion of 'v8::internal::RO_AMOMAX_W' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
  900 |     case RO_AMOMAX_W:
      |          ^~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:903:10: error: narrowing conversion of 'v8::internal::RO_AMOMINU_W' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
  903 |     case RO_AMOMINU_W:
      |          ^~~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:906:10: error: narrowing conversion of 'v8::internal::RO_AMOMAXU_W' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
  906 |     case RO_AMOMAXU_W:
      |          ^~~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:931:10: error: narrowing conversion of 'v8::internal::RO_AMOMIN_D' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
  931 |     case RO_AMOMIN_D:
      |          ^~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:934:10: error: narrowing conversion of 'v8::internal::RO_AMOMAX_D' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
  934 |     case RO_AMOMAX_D:
      |          ^~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:937:10: error: narrowing conversion of 'v8::internal::RO_AMOMINU_D' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
  937 |     case RO_AMOMINU_D:
      |          ^~~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:940:10: error: narrowing conversion of 'v8::internal::RO_AMOMAXU_D' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
  940 |     case RO_AMOMAXU_D:
      |          ^~~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc: In member function 'void v8::internal::Decoder::DecodeRFPType(v8::internal::Instruction*)':
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1010:10: error: narrowing conversion of 'v8::internal::RO_FCVT_W_S' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
 1010 |     case RO_FCVT_W_S: {  // RO_FCVT_WU_S , 64F RO_FCVT_L_S RO_FCVT_LU_S
      |          ^~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1031:10: error: narrowing conversion of 'v8::internal::RO_FMV' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
 1031 |     case RO_FMV: {  // RO_FCLASS_S
      |          ^~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1047:10: error: narrowing conversion of 'v8::internal::RO_FLE_S' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
 1047 |     case RO_FLE_S: {  // RO_FEQ_S RO_FLT_S RO_FLE_S
      |          ^~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1063:10: error: narrowing conversion of 'v8::internal::RO_FCVT_S_W' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
 1063 |     case RO_FCVT_S_W: {  // RO_FCVT_S_WU , 64F RO_FCVT_S_L RO_FCVT_S_LU
      |          ^~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1085:10: error: narrowing conversion of 'v8::internal::RO_FMV_W_X' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
 1085 |     case RO_FMV_W_X: {
      |          ^~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1168:10: error: narrowing conversion of 'v8::internal::RO_FLE_D' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
 1168 |     case RO_FLE_D: {  // RO_FEQ_D RO_FLT_D RO_FLE_D
      |          ^~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1184:37: error: narrowing conversion of '3791650899' from 'unsigned int' to 'int' [-Wnarrowing]
 1184 |     case (RO_FCLASS_D & kRFPTypeMask): {  // RO_FCLASS_D , 64D RO_FMV_X_D
      |                                     ^
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1203:10: error: narrowing conversion of 'v8::internal::RO_FCVT_W_D' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
 1203 |     case RO_FCVT_W_D: {  // RO_FCVT_WU_D , 64F RO_FCVT_L_D RO_FCVT_LU_D
      |          ^~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1224:10: error: narrowing conversion of 'v8::internal::RO_FCVT_D_W' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
 1224 |     case RO_FCVT_D_W: {  // RO_FCVT_D_WU , 64F RO_FCVT_D_L RO_FCVT_D_LU
      |          ^~~~~~~~~~~
../deps/v8/src/diagnostics/riscv64/disasm-riscv64.cc:1246:10: error: narrowing conversion of 'v8::internal::RO_FMV_D_X' from 'uint32_t' {aka 'unsigned int'} to 'int' [-Wnarrowing]
 1246 |     case RO_FMV_D_X: {
      |          ^~~~~~~~~~

**Comment by luyahan** [comment]
v8 of node js is old, please  wait new version v8 

V8 CL:
https://chromium-review.googlesource.com/c/v8/v8/+/2966209

**Comment by luyahan** [comment]
You also can build v8 wit our branch 
https://github.com/v8-riscv/node

**Comment by felixonmars** [comment]
Backported to nodejs at https://github.com/nodejs/node/pull/39827

Thanks for the porting effort!
