### ISSUE TITLE
Verification failure:  `F32SSub0(signalling_NaN)` from `mjsunit/wasm/float-constant-folding.js`

### ISSUE THREAD

**Issue by penguinwu** [riscv/v8#53]
**Describe the bug**
`float-constant-folding.js` fails to verify the result of `F32Sub0(signalling_NaN)`

**To Reproduce**
1. Use the simulated build following instructions [here](https://github.com/v8-riscv/v8/wiki/simulator-build) 
2. Run test/program 
```
out/riscv64.sim/d8 --test test/mjsunit/mjsunit.js test/mjsunit/wasm/float-constant-folding.js --random-seed=1881563104 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --expose-wasm
```

To debug, use wasm2wat translator in https://github.com/webassembly/wabt to convert the test case to human-readable WASM format.

```
F32: sNaN - 0 = qNaN
test/mjsunit/mjsunit.js:315: Failure: expected <2145386496> found <2143289344>

Stack: MjsUnitAssertionError
    at assertEquals test/mjsunit/mjsunit.js 405:7
    at              test/mjsunit/wasm/float-constant-folding.js 18:3
    at              test/mjsunit/wasm/float-constant-folding.js 19:3
    throw new MjsUnitAssertionError(message);
    ^
MjsUnitAssertionError
    at assertEquals test/mjsunit/mjsunit.js 405:7
    at              test/mjsunit/wasm/float-constant-folding.js 18:3
    at              test/mjsunit/wasm/float-constant-folding.js 19:3
```

**Expected behavior**
When the test passes, it produces no error message.

**Errors/Logs**

**Additional context**

This bug may cause failures in other tests such as `wasm/f32.js` and `wasm/f64.js`.

**Comment by DrRezaYazdani1** [comment]
This test fails on MIPS64 simulator run in a similar form as RISC-V. 
My evaluation is the implementation of  signalling NaN in the simulators both for MIPS64 and RISC-V is buggy. I suggest delay fixing this issue until running the test on the actual hardware.

Here is the fault and trace for MIPS64:
reza@olabg13083:~/v8/v8$ ./out.gn/mips64el_debug/d8 --test test/mjsunit/mjsunit.js test/mjsunit/wasm/float-constant-folding.js --random-seed=1881563104 --nohard-abort  --verif$
F32: sNaN - 0 = qNaN
Received signal 11 SEGV_MAPERR 000000000000

==== C stack trace ===============================

 [0x5563f8ffad21]
 [0x5563f8ffac70]
 [0x7f4858e898a0]
 [0x5563f6ff2c9c]
 [0x5563f6ff2bfd]
 [0x5563f6ff2bad]
 [0x5563f6ff2b1a]
 [0x5563f6ff25fd]
 [0x5563f70382f3]
 [0x5563f70a8ad4]
 [0x5563f79b4223]
 [0x5563f8045947]
 [0x5563f804daea]
 [0x5563f8055ae2]
 [0x5563f804154b]
 [0x5563f80599a9]
 [0x5563f8059d4a]
 [0x5563f805a74e]
 [0x5563f73dc84c]
 [0x5563f73dc691]
 [0x5563f73dc361]
 [0x5563f73d9ab4]
 [0x5563f73d8c71]
 [0x5563f742b2db]
 [0x5563f7199650]
 [0x5563f766513e]
 [0x5563f79e18c4]
 [0x5563f799c406]
 [0x5563f799b111]
 [0x5563f76439fc]
 [0x5563f7652ecb]
 [0x5563f7652988]
 [0x5563f8045947]
 [0x5563f804daea]
 [0x5563f8055ae2]
 [0x5563f804154b]
 [0x5563f80599a9]
 [0x5563f8059d4a]
 [0x5563f805a74e]
 [0x5563f73dc84c]
 [0x5563f73dc691]
[0x5563f73d8c71]
 [0x5563f704d244]
 [0x5563f6fd5a71]
 [0x5563f6fe32de]
 [0x5563f6fe5e7b]
 [0x5563f6fe72a8]
 [0x5563f6fe7772]
 [0x7f48582e9b97]
 [0x5563f6fbc9ca]
[end of stack trace]
Segmentation fault (core dumped)

**Comment by penguinwu** [comment]
I just noticed that in `mjsunit.status`, it listed the reasons why these tests were skipped. Let me validate that indeed on RISC-V, the sNaN and qNaN encoding differs from WASM, then we can safely skip these tests. I will assign this back to myself.

```
['arch in (mipsel, mips, mips64el, mips64, ppc, ppc64)', {
  # These tests fail because qNaN and sNaN values are encoded differently on
  # MIPS and ARM/x86 architectures
  'wasm/float-constant-folding': [SKIP],
}],
```

**Comment by derekztu22** [comment]
According to the RISC-V Spec:
<img width="669" alt="Screen Shot 2020-11-16 at 4 33 54 PM" src="https://user-images.githubusercontent.com/69054241/99324619-8bd9a980-2829-11eb-847a-41532bb2c0f7.png">
Since from what I understand this test is doing an fsub.s(sNaN, 0), the result will always be the canonical NaN: 0x7fc00000 (2143289344) instead of the expected quiet NaN 0x7fe00000: (2145386496).

**Comment by qjivy** [comment]
Retry this case on the riscv-sparkplug-dev branch with commit id c7b10d4, **same error.**

**Comment by qjivy** [comment]
Retry this case ,  same error.
main branch commitid:
```
commit 35e2b11b2d2e6a8653b802613a9c496f64e4bd22 (origin/master, origin/main, origin/HEAD)
Author: Nico Hartmann <nicohartmann@chromium.org>
Date:   Tue Jul 20 12:13:01 2021 +0200
```
```
./out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/wasm/float-constant-folding.js --random-seed=1881563104 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --expose-wasm
Warning: unknown flag --enable-slow-asserts.
Try --help for options
F32: sNaN - 0 = qNaN
test/mjsunit/mjsunit.js:325: Failure: expected <2145386496> found <2143289344>

Stack: MjsUnitAssertionError
    at assertEquals test/mjsunit/mjsunit.js 415:7
    at              test/mjsunit/wasm/float-constant-folding.js 18:3
    at              test/mjsunit/wasm/float-constant-folding.js 19:3
    throw new MjsUnitAssertionError(message);
    ^
MjsUnitAssertionError
    at assertEquals test/mjsunit/mjsunit.js 415:7
    at              test/mjsunit/wasm/float-constant-folding.js 18:3
    at              test/mjsunit/wasm/float-constant-folding.js 19:3



#
# Fatal error in , line 0
# Check failed: unwinding_info_offset() <= MetadataSize().
#
#
#
#FailureMessage Object: 0x7ffdf4c209d0
==== C stack trace ===============================

    ./out/riscv64.release/d8(v8::base::debug::StackTrace::StackTrace()+0x13) [0x5628acec2793]
    ./out/riscv64.release/d8(+0x14dbfab) [0x5628acec1fab]
    ./out/riscv64.release/d8(V8_Fatal(char const*, ...)+0x145) [0x5628aceb6b75]
    ./out/riscv64.release/d8(v8::internal::Code::CodeVerify(v8::internal::Isolate*)+0x249) [0x5628ac351389]
    ./out/riscv64.release/d8(v8::internal::HeapObject::HeapObjectVerify(v8::internal::Isolate*)+0x81c) [0x5628ac3503ec]
    ./out/riscv64.release/d8(v8::internal::Object::ObjectVerify(v8::internal::Isolate*)+0x48) [0x5628ac34fb38]
    ./out/riscv64.release/d8(v8::internal::PagedSpace::Verify(v8::internal::Isolate*, v8::internal::ObjectVisitor*)+0x258) [0x5628ac4740f8]
    ./out/riscv64.release/d8(v8::internal::Heap::Verify()+0x299) [0x5628ac3f0a59]
    ./out/riscv64.release/d8(v8::internal::Heap::StartTearDown()+0x47) [0x5628ac3fac97]
    ./out/riscv64.release/d8(v8::internal::Isolate::Deinit()+0x280) [0x5628ac384100]
    ./out/riscv64.release/d8(v8::internal::Isolate::Delete(v8::internal::Isolate*)+0x61) [0x5628ac383de1]
    ./out/riscv64.release/d8(v8::Shell::OnExit(v8::Isolate*)+0x16) [0x5628ac201296]
    ./out/riscv64.release/d8(v8::Shell::Main(int, char**)+0xe20) [0x5628ac20bc30]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f8179c92bf7]
    ./out/riscv64.release/d8(_start+0x2a) [0x5628ac1eddca]
Received signal 6
Aborted
qjivy@plc
```

**Comment by luyahan** [comment]
riscv always ouput canonical NaN: 0x7fc00000
wasm expectes quiet NaN 0x7fe00000
